### ISSUE TITLE
Feature request: Pictures in issue comments shall be displayed

### ISSUE THREAD

**Issue by juengling** [mgvora/gitplus_for_gitlab#17]
I think, pictures in issue comments (notes) shall be displayed. And I'ld like to be able to add pics to an existing or new issue.

**Comment by thelooter** [comment]
I'm starting to implement new Features over at [thelooter/gitplus_for_gitlab](https://github.com/thelooter/gitplus_for_gitlab) since this Repository seems to be dead. If you still have a need for this feature, feel free to raise a issue over there

**Comment by juengling** [comment]
> I'm starting to implement new Features over at [thelooter/gitplus_for_gitlab](https://github.com/thelooter/gitplus_for_gitlab) since this Repository seems to be dead. If you still have a need for this feature, feel free to raise a issue over there

Done: https://github.com/thelooter/labplus_for_gitlab/issues/23
