### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by PhilDevProg** [mgvora/gitplus_for_gitlab#4]
Since version 1.1.0 I can't login into my GitLab account anymore. There always just pops up a popup with the message 'Unauthorized'. It works with other GitLab Apps so it seems to be an issue of Git+. Both login methode
s don't work. When I click on the 'Get Access Token' button the WebView can't load the website while my browser can load it. I get this error message from the WebView: `net::ERR_CACHE_MISS`

I already tried clearing the cache, removing all app data and reinstalling the app but nothing helped.

**Comment by mgvora** [comment]
Hello, 
Which android version are you using?

**Comment by PhilDevProg** [comment]
Android 12 (SQ3A.220705.003.A1) on a Google Pixel 4a

**Comment by mgvora** [comment]
Hello,
the issue should be resolved in the latest version 1.1.1
Could you verify if everything is ok?

**Comment by PhilDevProg** [comment]
Yes, everything works fine again

**Comment by mgvora** [comment]
Thank you for the notice and verification.
